using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MoveVN.Infrastructure.Persistence.Migrations
{
    public partial class CompleteDisputeOnlyWorkflow : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS admin_close_reason text;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS closed_at timestamp with time zone;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS closed_by bigint;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS customer_external_confirmed boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS customer_external_confirmed_at timestamp with time zone;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS decided_by bigint;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS decision_issued_at timestamp with time zone;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS external_settlement_amount numeric NOT NULL DEFAULT 0;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS owner_external_confirmed boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS owner_external_confirmed_at timestamp with time zone;
                ALTER TABLE "Disputes" ADD COLUMN IF NOT EXISTS platform_settled_amount numeric NOT NULL DEFAULT 0;

                CREATE TABLE IF NOT EXISTS "DisputeEvidenceSubmissions" (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dispute_id bigint NOT NULL,
                    submitted_by bigint NOT NULL,
                    submitted_role text NOT NULL,
                    message text NOT NULL,
                    evidence_urls text,
                    created_at timestamp with time zone NOT NULL
                );

                CREATE INDEX IF NOT EXISTS "IX_DisputeEvidenceSubmissions_dispute_id_submitted_by"
                    ON "DisputeEvidenceSubmissions" (dispute_id, submitted_by);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS "DisputeEvidenceSubmissions";
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS admin_close_reason;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS closed_at;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS closed_by;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS customer_external_confirmed;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS customer_external_confirmed_at;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS decided_by;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS decision_issued_at;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS external_settlement_amount;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS owner_external_confirmed;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS owner_external_confirmed_at;
                ALTER TABLE "Disputes" DROP COLUMN IF EXISTS platform_settled_amount;
                """);
        }
    }
}
