CREATE TABLE IF NOT EXISTS "Promotions" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    discount_type text NOT NULL DEFAULT 'Fixed',
    discount_value numeric(15,2) NOT NULL,
    max_discount_amount numeric(15,2),
    min_order_amount numeric(15,2),
    vehicle_type text NOT NULL DEFAULT 'All',
    who_bears text NOT NULL DEFAULT 'System',
    owner_bears_percent numeric(5,2),
    owner_id bigint,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone,
    max_usage_count integer NOT NULL DEFAULT 100,
    usage_count integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_Promotions" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Promotions_code" ON "Promotions" (code);
CREATE INDEX IF NOT EXISTS "IX_Promotions_is_active_start_at_end_at" ON "Promotions" (is_active, start_at, end_at);

CREATE TABLE IF NOT EXISTS "PromotionUsages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    promotion_id bigint NOT NULL,
    booking_id bigint NOT NULL,
    user_id bigint NOT NULL,
    discount_amount numeric(15,2) NOT NULL,
    system_paid_amount numeric(15,2) NOT NULL DEFAULT 0,
    owner_paid_amount numeric(15,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_PromotionUsages" PRIMARY KEY (id),
    CONSTRAINT "FK_PromotionUsages_Promotions_promotion_id" FOREIGN KEY (promotion_id) REFERENCES "Promotions" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_PromotionUsages_Bookings_booking_id" FOREIGN KEY (booking_id) REFERENCES "Bookings" (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_PromotionUsages_promotion_id" ON "PromotionUsages" (promotion_id);
CREATE INDEX IF NOT EXISTS "IX_PromotionUsages_booking_id" ON "PromotionUsages" (booking_id);
