CREATE TABLE "Area" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    province text NOT NULL,
    district text NOT NULL,
    pricing_region_id integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_Area" PRIMARY KEY (id)
);


CREATE TABLE "AspNetRoles" (
    id uuid NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY (id)
);


CREATE TABLE "AspNetUsers" (
    id uuid NOT NULL,
    full_name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY (id)
);


CREATE TABLE "AuditLogs" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    actor_id bigint,
    actor_role text,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint,
    old_value text,
    new_value text,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY (id)
);


CREATE TABLE "BlockedDates" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text,
    CONSTRAINT "PK_BlockedDates" PRIMARY KEY (id)
);


CREATE TABLE "Bookings" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_code text NOT NULL,
    customer_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    total_days integer NOT NULL,
    base_price numeric NOT NULL,
    platform_fee numeric NOT NULL,
    deposit_amount numeric NOT NULL,
    total_amount numeric NOT NULL,
    pickup_address text NOT NULL,
    return_address text NOT NULL,
    customer_note text,
    status text NOT NULL,
    risk_score numeric,
    cancelled_by bigint,
    cancel_reason text,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    platform_fee_rule_id bigint,
    platform_fee_type text NOT NULL,
    platform_fee_value numeric NOT NULL,
    CONSTRAINT "PK_Bookings" PRIMARY KEY (id)
);


CREATE TABLE "BookingStatusHistory" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    from_status text,
    to_status text NOT NULL,
    changed_by bigint,
    note text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BookingStatusHistory" PRIMARY KEY (id)
);


CREATE TABLE "CashbackRules" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    trust_tier text NOT NULL,
    cashback_percent numeric NOT NULL,
    min_deposit_reduction numeric NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CashbackRules" PRIMARY KEY (id)
);


CREATE TABLE "CheckInOutImages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    inspection_id bigint,
    image_url text NOT NULL,
    image_type text NOT NULL,
    uploaded_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CheckInOutImages" PRIMARY KEY (id)
);


CREATE TABLE "Contracts" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    contract_number text NOT NULL,
    pdf_url text,
    customer_signed_at timestamp with time zone,
    owner_signed_at timestamp with time zone,
    customer_signature_data text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Contracts" PRIMARY KEY (id)
);


CREATE TABLE "CustomerProfiles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    date_of_birth date,
    address text,
    national_id text,
    national_id_hash text,
    national_id_masked text,
    national_id_verified boolean NOT NULL,
    driver_license_number text,
    driver_license_verified boolean NOT NULL,
    preferred_vehicle_type text,
    CONSTRAINT "PK_CustomerProfiles" PRIMARY KEY (id)
);


CREATE TABLE "DemandForecasts" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    district text NOT NULL,
    vehicle_type text NOT NULL,
    forecast_date date NOT NULL,
    predicted_demand integer NOT NULL,
    model_version text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DemandForecasts" PRIMARY KEY (id)
);


CREATE TABLE "Disputes" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    report_id bigint,
    opened_by bigint NOT NULL,
    assigned_staff_id bigint,
    status text NOT NULL,
    resolution text,
    compensation_amount numeric,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Disputes" PRIMARY KEY (id)
);


CREATE TABLE "DriverLicenseClasses" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    display_name text NOT NULL,
    description text NOT NULL,
    system_version text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_DriverLicenseClasses" PRIMARY KEY (id)
);


CREATE TABLE "FeatureFlags" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    flag_key text NOT NULL,
    is_enabled boolean NOT NULL,
    rollout_percent smallint NOT NULL,
    allowed_roles text,
    description text,
    updated_by bigint,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FeatureFlags" PRIMARY KEY (id)
);


CREATE TABLE "InspectionReports" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    type text NOT NULL,
    staff_id bigint NOT NULL,
    odometer_km integer,
    fuel_level text,
    damage_noted boolean NOT NULL,
    damage_description text,
    report_pdf_url text,
    customer_signature_url text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InspectionReports" PRIMARY KEY (id)
);


CREATE TABLE "MLPredictionLogs" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    model_version text NOT NULL,
    risk_score numeric NOT NULL,
    feature_snapshot text NOT NULL,
    top_risk_factors text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MLPredictionLogs" PRIMARY KEY (id)
);


CREATE TABLE "NotificationPreferences" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    in_app_enabled boolean NOT NULL,
    email_enabled boolean NOT NULL,
    sms_enabled boolean NOT NULL,
    zalo_enabled boolean NOT NULL,
    quiet_hours_start time without time zone,
    quiet_hours_end time without time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY (id)
);


CREATE TABLE "Notifications" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    data_json text,
    channel text NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp with time zone,
    sent_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY (id)
);


CREATE TABLE "OtpCodes" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    email text NOT NULL,
    otp_code_hash text NOT NULL,
    purpose text NOT NULL,
    is_used boolean NOT NULL,
    attempts smallint NOT NULL,
    ip_address text,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OtpCodes" PRIMARY KEY (id)
);


CREATE TABLE "OwnerProfiles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    bank_account_number text,
    bank_name text,
    bank_account_holder_name text,
    tier text NOT NULL,
    commission_rate numeric NOT NULL,
    total_trips integer NOT NULL,
    average_rating numeric,
    is_verified boolean NOT NULL,
    verified_at timestamp with time zone,
    CONSTRAINT "PK_OwnerProfiles" PRIMARY KEY (id)
);


CREATE TABLE "Payments" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    payer_id bigint NOT NULL,
    type text NOT NULL,
    amount numeric NOT NULL,
    currency text NOT NULL,
    gateway text NOT NULL,
    gateway_transaction_id text,
    status text NOT NULL,
    idempotency_key text NOT NULL,
    paid_at timestamp with time zone,
    note text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY (id)
);


CREATE TABLE "Permissions" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    description text,
    CONSTRAINT "PK_Permissions" PRIMARY KEY (id)
);


CREATE TABLE "PlatformFeeRules" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    target_type text NOT NULL,
    target_id bigint,
    fee_type text NOT NULL,
    fee_value numeric NOT NULL,
    min_fee numeric,
    max_fee numeric,
    priority integer NOT NULL,
    start_at timestamp with time zone,
    end_at timestamp with time zone,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlatformFeeRules" PRIMARY KEY (id)
);


CREATE TABLE "PricingRegion" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code text NOT NULL,
    description text,
    coefficient numeric NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_PricingRegion" PRIMARY KEY (id)
);


CREATE TABLE "RefreshTokens" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    token_hash text NOT NULL,
    device_info text,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY (id)
);


CREATE TABLE "Reports" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    reporter_id bigint NOT NULL,
    report_type text NOT NULL,
    description text NOT NULL,
    evidence_urls text,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reports" PRIMARY KEY (id)
);


CREATE TABLE "Reviews" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    booking_id bigint,
    reviewer_id bigint NOT NULL,
    reviewee_id bigint NOT NULL,
    vehicle_id bigint,
    rating smallint NOT NULL,
    cleanliness_score smallint,
    accuracy_score smallint,
    support_score smallint,
    comment text,
    is_public boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY (id)
);


CREATE TABLE "RolePermissions" (
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY (role_id, permission_id)
);


CREATE TABLE "Roles" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    CONSTRAINT "PK_Roles" PRIMARY KEY (id)
);


CREATE TABLE "StaffProfiles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    employee_code text NOT NULL,
    department text,
    supervisor_id bigint,
    CONSTRAINT "PK_StaffProfiles" PRIMARY KEY (id)
);


CREATE TABLE "SupportTickets" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    ticket_number text NOT NULL,
    category text NOT NULL,
    subject text NOT NULL,
    status text NOT NULL,
    assigned_staff_id bigint,
    priority text NOT NULL,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY (id)
);


CREATE TABLE "SystemConfig" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    config_key text NOT NULL,
    config_value text NOT NULL,
    data_type text NOT NULL,
    description text,
    updated_by bigint,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SystemConfig" PRIMARY KEY (id)
);


CREATE TABLE "TicketMessages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticket_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    message text NOT NULL,
    attachment_urls text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TicketMessages" PRIMARY KEY (id)
);


CREATE TABLE "TrustScores" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    score numeric NOT NULL,
    tier text NOT NULL,
    completed_trips integer NOT NULL,
    cancellation_count integer NOT NULL,
    report_count integer NOT NULL,
    average_rating numeric,
    last_calculated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TrustScores" PRIMARY KEY (id)
);


CREATE TABLE "UserRoles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    role_id integer NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    assigned_by bigint,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY (id)
);


CREATE TABLE "Users" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    password_hash text,
    external_id text,
    auth_provider text,
    full_name text NOT NULL,
    phone text,
    avatar_url text,
    status text NOT NULL,
    is_email_verified boolean NOT NULL,
    last_login_at timestamp with time zone,
    last_seen_at timestamp with time zone,
    is_online boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY (id)
);


CREATE TABLE "UserSessions" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    connection_id text NOT NULL,
    device_type text,
    ip_address text,
    user_agent text,
    connected_at timestamp with time zone NOT NULL,
    last_heartbeat_at timestamp with time zone NOT NULL,
    disconnected_at timestamp with time zone,
    CONSTRAINT "PK_UserSessions" PRIMARY KEY (id)
);


CREATE TABLE "VehicleBrand" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    vehicle_type text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_VehicleBrand" PRIMARY KEY (id)
);


CREATE TABLE "VehicleDocuments" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    doc_type text NOT NULL,
    file_url text NOT NULL,
    file_public_id text,
    expiry_date date,
    verified boolean NOT NULL,
    is_current boolean NOT NULL DEFAULT TRUE,
    verification_status text NOT NULL DEFAULT 'Pending',
    verification_provider text,
    processed_at timestamp with time zone,
    decision_reason text,
    ocr_license_plate text,
    ocr_brand text,
    ocr_model text,
    ocr_engine_number text,
    ocr_chassis_number text,
    ocr_confidence numeric(15,2),
    deleted_at timestamp with time zone,
    delete_reason text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleDocuments" PRIMARY KEY (id)
);


CREATE TABLE "VehicleFeature" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    vehicle_type text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_VehicleFeature" PRIMARY KEY (id)
);


CREATE TABLE "VehicleFeatureMapping" (
    vehicle_id bigint NOT NULL,
    feature_id integer NOT NULL,
    CONSTRAINT "PK_VehicleFeatureMapping" PRIMARY KEY (vehicle_id, feature_id)
);


CREATE TABLE "VehicleImages" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    image_url text NOT NULL,
    is_primary boolean NOT NULL,
    sort_order smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleImages" PRIMARY KEY (id)
);


CREATE TABLE "VehicleModel" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    brand_id integer NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_VehicleModel" PRIMARY KEY (id)
);


CREATE TABLE "VehiclePricing" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    pricing_mode text NOT NULL,
    fixed_price_per_day numeric,
    auto_min_price numeric,
    auto_max_price numeric,
    current_price_per_day numeric NOT NULL,
    last_calculated_at timestamp with time zone,
    last_updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehiclePricing" PRIMARY KEY (id)
);


CREATE TABLE "VerificationRequests" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    type text NOT NULL,
    front_image_public_id text NOT NULL,
    back_image_public_id text,
    front_image_url text,
    back_image_url text,
    selfie_url text,
    status text NOT NULL,
    external_provider text,
    external_result_json jsonb,
    confidence numeric(15,2),
    decision_reason text,
    processed_at timestamp with time zone,
    reviewed_by bigint,
    reviewed_at timestamp with time zone,
    rejection_reason text,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT "PK_VerificationRequests" PRIMARY KEY (id)
);


CREATE TABLE "Wallets" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    balance numeric NOT NULL,
    total_earned numeric NOT NULL,
    total_spent numeric NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Wallets" PRIMARY KEY (id)
);


CREATE TABLE "WalletTransactions" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    wallet_id bigint NOT NULL,
    type text NOT NULL,
    amount numeric NOT NULL,
    balance_after numeric NOT NULL,
    reference_id bigint,
    idempotency_key text NOT NULL,
    note text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WalletTransactions" PRIMARY KEY (id)
);


CREATE TABLE "AspNetRoleClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY (id),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_role_id" FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY (id),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_user_id" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_user_id" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_role_id" FOREIGN KEY (role_id) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_user_id" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_user_id" FOREIGN KEY (user_id) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);


CREATE TABLE "DriverLicenseClassCompatibility" (
    license_class_id integer NOT NULL,
    allowed_required_license_class_id integer NOT NULL,
    CONSTRAINT "PK_DriverLicenseClassCompatibility" PRIMARY KEY (license_class_id, allowed_required_license_class_id),
    CONSTRAINT "FK_DriverLicenseClassCompatibility_DriverLicenseClasses_allowe~" FOREIGN KEY (allowed_required_license_class_id) REFERENCES "DriverLicenseClasses" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_DriverLicenseClassCompatibility_DriverLicenseClasses_licens~" FOREIGN KEY (license_class_id) REFERENCES "DriverLicenseClasses" (id) ON DELETE CASCADE
);


CREATE TABLE "PricingRules" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    rule_type text NOT NULL,
    multiplier numeric,
    fixed_price numeric,
    brand_id integer,
    model_id integer,
    pricing_region_id integer,
    priority integer NOT NULL,
    start_date date,
    end_date date,
    is_active boolean NOT NULL,
    CONSTRAINT "PK_PricingRules" PRIMARY KEY (id),
    CONSTRAINT "FK_PricingRules_PricingRegion_pricing_region_id" FOREIGN KEY (pricing_region_id) REFERENCES "PricingRegion" (id) ON DELETE SET NULL,
    CONSTRAINT "FK_PricingRules_VehicleBrand_brand_id" FOREIGN KEY (brand_id) REFERENCES "VehicleBrand" (id) ON DELETE SET NULL,
    CONSTRAINT "FK_PricingRules_VehicleModel_model_id" FOREIGN KEY (model_id) REFERENCES "VehicleModel" (id) ON DELETE SET NULL
);


CREATE TABLE "VehicleModelPricing" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    model_id integer NOT NULL,
    base_price numeric NOT NULL,
    suggested_min_price numeric NOT NULL,
    suggested_max_price numeric NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleModelPricing" PRIMARY KEY (id),
    CONSTRAINT "FK_VehicleModelPricing_VehicleModel_model_id" FOREIGN KEY (model_id) REFERENCES "VehicleModel" (id) ON DELETE RESTRICT
);


CREATE TABLE "VehicleModelVariant" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    model_id integer NOT NULL,
    name text NOT NULL,
    vehicle_type text NOT NULL,
    seat_count smallint,
    transmission text,
    fuel_type text,
    body_type text,
    drivetrain text,
    bike_type text,
    engine_capacity text,
    required_license_class_id integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleModelVariant" PRIMARY KEY (id),
    CONSTRAINT "FK_VehicleModelVariant_DriverLicenseClasses_required_license_c~" FOREIGN KEY (required_license_class_id) REFERENCES "DriverLicenseClasses" (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleModelVariant_VehicleModel_model_id" FOREIGN KEY (model_id) REFERENCES "VehicleModel" (id) ON DELETE RESTRICT
);


CREATE TABLE "OwnerApplications" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    status text NOT NULL,
    national_id_verification_request_id bigint,
    bank_name text,
    bank_account_number text,
    bank_account_holder_name text,
    submitted_at timestamp with time zone,
    approved_at timestamp with time zone,
    approved_by bigint,
    rejected_at timestamp with time zone,
    rejected_by bigint,
    rejection_reason text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OwnerApplications" PRIMARY KEY (id),
    CONSTRAINT "FK_OwnerApplications_Users_user_id" FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE CASCADE,
    CONSTRAINT "FK_OwnerApplications_VerificationRequests_national_id_verifica~" FOREIGN KEY (national_id_verification_request_id) REFERENCES "VerificationRequests" (id) ON DELETE SET NULL
);


CREATE TABLE "CarDetail" (
    vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY,
    model_variant_id integer,
    CONSTRAINT "PK_CarDetail" PRIMARY KEY (vehicle_id),
    CONSTRAINT "FK_CarDetail_VehicleModelVariant_model_variant_id" FOREIGN KEY (model_variant_id) REFERENCES "VehicleModelVariant" (id) ON DELETE RESTRICT
);


CREATE TABLE "MotorbikeDetail" (
    vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY,
    model_variant_id integer,
    CONSTRAINT "PK_MotorbikeDetail" PRIMARY KEY (vehicle_id),
    CONSTRAINT "FK_MotorbikeDetail_VehicleModelVariant_model_variant_id" FOREIGN KEY (model_variant_id) REFERENCES "VehicleModelVariant" (id) ON DELETE RESTRICT
);


CREATE TABLE "Vehicles" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    owner_id bigint NOT NULL,
    brand_id integer NOT NULL,
    model_id integer NOT NULL,
    variant_id integer,
    vehicle_type text NOT NULL,
    year smallint NOT NULL,
    license_plate text NOT NULL,
    odometer_km integer,
    description text,
    address text NOT NULL,
    area_id integer,
    latitude numeric,
    longitude numeric,
    price_per_day numeric NOT NULL,
    deposit_percent integer NOT NULL DEFAULT 0,
    security_deposit_amount numeric(15,2) NOT NULL DEFAULT 0,
    security_requires_deposit boolean NOT NULL DEFAULT false,
    status text NOT NULL,
    approved_by bigint,
    approved_at timestamp with time zone,
    rejection_reason text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Vehicles" PRIMARY KEY (id),
    CONSTRAINT "FK_Vehicles_Area_area_id" FOREIGN KEY (area_id) REFERENCES "Area" (id) ON DELETE SET NULL,
    CONSTRAINT "FK_Vehicles_VehicleModelVariant_variant_id" FOREIGN KEY (variant_id) REFERENCES "VehicleModelVariant" (id) ON DELETE SET NULL
);


CREATE UNIQUE INDEX "IX_Area_province_district" ON "Area" (province, district);


CREATE INDEX "IX_AspNetRoleClaims_role_id" ON "AspNetRoleClaims" (role_id);


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalized_name);


CREATE INDEX "IX_AspNetUserClaims_user_id" ON "AspNetUserClaims" (user_id);


CREATE INDEX "IX_AspNetUserLogins_user_id" ON "AspNetUserLogins" (user_id);


CREATE INDEX "IX_AspNetUserRoles_role_id" ON "AspNetUserRoles" (role_id);


CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalized_email);


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalized_user_name);


CREATE INDEX "IX_CarDetail_model_variant_id" ON "CarDetail" (model_variant_id);


CREATE INDEX "IX_CustomerProfiles_national_id_hash" ON "CustomerProfiles" (national_id_hash);


CREATE INDEX "IX_DriverLicenseClassCompatibility_allowed_required_license_cl~" ON "DriverLicenseClassCompatibility" (allowed_required_license_class_id);


CREATE UNIQUE INDEX "IX_DriverLicenseClasses_code" ON "DriverLicenseClasses" (code);


CREATE INDEX "IX_MotorbikeDetail_model_variant_id" ON "MotorbikeDetail" (model_variant_id);


CREATE INDEX "IX_OwnerApplications_national_id_verification_request_id" ON "OwnerApplications" (national_id_verification_request_id);


CREATE INDEX "IX_OwnerApplications_user_id_status" ON "OwnerApplications" (user_id, status);


CREATE UNIQUE INDEX "IX_PricingRegion_code" ON "PricingRegion" (code);


CREATE INDEX "IX_PricingRules_brand_id" ON "PricingRules" (brand_id);


CREATE INDEX "IX_PricingRules_model_id" ON "PricingRules" (model_id);


CREATE INDEX "IX_PricingRules_pricing_region_id" ON "PricingRules" (pricing_region_id);


CREATE UNIQUE INDEX "IX_VehicleBrand_name_vehicle_type" ON "VehicleBrand" (name, vehicle_type);


CREATE INDEX "IX_VehicleDocuments_vehicle_id" ON "VehicleDocuments" (vehicle_id);


CREATE INDEX "IX_VehicleDocuments_vehicle_id_is_current" ON "VehicleDocuments" (vehicle_id, is_current);


CREATE INDEX "IX_VehicleDocuments_verification_status" ON "VehicleDocuments" (verification_status);


CREATE UNIQUE INDEX "IX_VehicleModelPricing_model_id" ON "VehicleModelPricing" (model_id);


CREATE INDEX "IX_VehicleModelVariant_model_id_name" ON "VehicleModelVariant" (model_id, name);


CREATE INDEX "IX_VehicleModelVariant_required_license_class_id" ON "VehicleModelVariant" (required_license_class_id);


CREATE INDEX "IX_Vehicles_area_id" ON "Vehicles" (area_id);


CREATE INDEX "IX_Vehicles_owner_id_status_vehicle_type" ON "Vehicles" (owner_id, status, vehicle_type);


CREATE INDEX "IX_Vehicles_variant_id" ON "Vehicles" (variant_id);


