export const endpoints = {
  auth: {
    register: "/api/auth/register",
    verifyOtp: "/api/auth/verify-otp",
    resendOtp: "/api/auth/resend-otp",
    googleLogin: "/api/auth/google-login",
    login: "/api/auth/login",
    refreshToken: "/api/auth/refresh-token",
    logout: "/api/auth/logout",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
    changePassword: "/api/auth/change-password",
    me: "/api/auth/me",
  },
  admin: {
    users: "/api/admin/users",
    vehicles: "/api/admin/vehicles",
    vehicleBrands: "/api/admin/vehicle-brands",
    vehicleModels: "/api/admin/vehicle-models",
    vehicleModelVariants: "/api/admin/vehicle-model-variants",
    driverLicenseClasses: "/api/admin/driver-license-classes",
    vehicleFeatures: "/api/admin/vehicle-features",
    pricingRegions: "/api/admin/pricing-regions",
    areas: "/api/admin/areas",
    vehicleModelPricings: "/api/admin/vehicle-model-pricings",
    pricingRules: "/api/admin/pricing-rules",
    platformFeeRules: "/api/admin/platform-fee-rules",
  },
  vehicles: {
    my: "/api/vehicles/my",
    byId: (id: number) => `/api/vehicles/${id}`,
    uploadDocument: (id: number) => `/api/vehicles/${id}/documents`,
    uploadImage: "/api/vehicles/images",
    pricing: (id: number) => `/api/vehicles/${id}/pricing`,
    pricingSuggestion: "/api/vehicles/pricing/suggestion",
    toggleStatus: (id: number) => `/api/vehicles/${id}/toggle-status`,
    base: "/api/vehicles",
  },
  staff: {
    vehicles: "/api/staff/vehicles",
  },
  catalog: {
    brands: "/api/catalog/brands",
    models: "/api/catalog/models",
    variants: "/api/catalog/variants",
    features: "/api/catalog/features",
    areas: "/api/catalog/areas",
    pricingRegions: "/api/catalog/pricing-regions",
  },
  publicVehicles: {
    list: "/api/public/vehicles",
    byId: (id: number) => `/api/public/vehicles/${id}`,
  },
  notifications: {
    base: "/api/notifications",
    unreadCount: "/api/notifications/unread-count",
    markRead: (id: number) => `/api/notifications/${id}/read`,
    markAllRead: "/api/notifications/read-all",
  },
  swaggerJson: "/swagger/v1/swagger.json",
};
